export enum Platforms {
	Ps1 = 'ps1',
	Ps2 = 'ps2',
	Ps3 = 'ps3',
	Ps4 = 'ps4',
	Ps5 = 'ps5',
	Psp = 'psp',
	PsVita = 'ps_vita',
	OriginalXbox = 'original_xbox',
	Xbox360 = 'xbox_360',
	XboxOne = 'xbox_one',
	XboxSeriesXandS = 'xbox_series_x_s',
	SegaMegaDrive = 'sega_mega_drive',
	wii = 'wii',
	Switch = 'switch',
	NES = 'nes',
	DS = 'ds',
	PC = 'pc',	
}

export const PlatformLabels: Record<Platforms, string> = {
	[Platforms.Ps1]: 'PS1',
	[Platforms.Ps2]: 'PS2',
	[Platforms.Ps3]: 'PS3',
	[Platforms.Ps4]: 'PS4',
	[Platforms.Ps5]: 'PS5',
	[Platforms.Psp]: 'PSP',
	[Platforms.PsVita]: 'PS Vita',
	[Platforms.OriginalXbox]: 'Original Xbox',
	[Platforms.Xbox360]: 'Xbox 360',
	[Platforms.XboxOne]: 'Xbox One',
	[Platforms.XboxSeriesXandS]: 'Xbox Series X|S',
	[Platforms.SegaMegaDrive]: 'Sega Mega Drive',
	[Platforms.wii]: 'Wii',
	[Platforms.Switch]: 'Switch',
	[Platforms.NES]: 'NES',
	[Platforms.DS]: 'DS',
	[Platforms.PC]: 'PC',
};
